### ISSUE TITLE
这个是SS？

### ISSUE THREAD

**Issue by tislam8888** [xiaokaixuan/gost-heroku#1]
小白 不知道怎么用啊
还用 现在还敢部署在heroku
是不是太冒险了

**Comment by xiaokaixuan** [comment]
基于websocket传输的SS

**Comment by tislam8888** [comment]
@xiaokaixuan 
怎么用啊 下载了那个可执行性文件
打不开
还有我现在不敢部署heroku
被封了两个号了

**Comment by xiaokaixuan** [comment]
先部署，再用客户端连，readme里写了。
不建议长期使用heroku翻墙

**Comment by tislam8888** [comment]
@xiaokaixuan 
客户端就是Windows安装的那个是吗
我经常更新core 现在都是3.35
新的core 容易被heroku封号？

**Comment by xiaokaixuan** [comment]
不是  服务用的是3.10 最好保持一致

**Comment by tislam8888** [comment]
@xiaokaixuan 
你的heroku有被封到吗

**Comment by xiaokaixuan** [comment]
我用的少 自己搭建的VPS

**Comment by xiaokaixuan** [comment]
@tislam8888 账号封杀了之后是什么提示？你用的国产邮箱注册的吗？最好翻墙注册账号

**Comment by tislam8888** [comment]
@xiaokaixuan 
我用的是gmail的
就是部署过onplus的那个shadowsocks-heroku
和 v2hero

**Comment by tislam8888** [comment]
@xiaokaixuan 
登陆heroku
就提示
Your account has been suspended. If you believe this is an error, please contact suspended-account@heroku.com

**Comment by xiaokaixuan** [comment]
@tislam8888 那就没办法了 别用v2ray了 换个试下吧

**Comment by tislam8888** [comment]
@xiaokaixuan 
heroku
用了快大半年了
其实出事情 最主要是因为现在那些煞笔 公开发v2ray-heroku的教程上youtube
一堆傻瓜疯狂部署 不封号才奇怪 搞得我们这些也没法用了

**Comment by tislam8888** [comment]
@xiaokaixuan 
你会不会部署 openshift的v2ray
帮忙看看为什么 老是不行啊
日志显示 
Failed Create Pod Sand Box

Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "db0b2dc7a4ef9e2ab25ee7a91b3169102117ee388a04c36f4109682aa73dc771" network for pod "cundanx0g-1-deploy": NetworkPlugin cni failed to set up pod "cundanx0g-1-deploy_myopsv2ra9" network: failed to send CNI request: Post http://dummy/: dial unix /var/run/openshift-sdn/cni-server.sock: connect: connection refused, failed to clean up sandbox container "db0b2dc7a4ef9e2ab25ee7a91b3169102117ee388a04c36f4109682aa73dc771" network for pod "cundanx0g-1-deploy": NetworkPlugin cni failed to teardown pod "cundanx0g-1-deploy_myopsv2ra9" network: failed to send CNI request: Post http://dummy/: dial unix /var/run/openshift-sdn/cni-server.sock: connect: connection refused]

**Comment by xiaokaixuan** [comment]
@tislam8888 openshift docker不支持root运行 并且openshift很容易被封禁 我搭建了一次没怎么用就被封了

**Comment by tislam8888** [comment]
@xiaokaixuan 
干嘛我看他们都是这样子的配置文件部署的 都可以
不支持root运行 怎么解决

**Comment by bclswl0827** [comment]
试试用日本的Arukas Docker部署

**Comment by bclswl0827** [comment]
> 不支持root运行 怎么解决

还是花钱买台便宜点的VPS来折腾吧

**Comment by bclswl0827** [comment]
其实可以试下多年前的GoAgent+PHP来翻墙，把GoAgent PHP部署在Heroku、OpenShift或是000Webhost，然后GoAgent本地端填入服务器端文件的路径就可以翻墙了
但是这东西速度很慢

**Comment by bclswl0827** [comment]
Heroku 的好像已经失效了... 应用好像会被删掉
[部署在 Openshift 上的 V2ray 镜像](https://github.com/bclswl0827/v2ray-openshift)，这个可以正常部署，试试 ?

**Comment by tislam8888** [comment]
你有用v2ray吗
现在更新了最新的v4.1 core
就不能用了

**Comment by tislam8888** [comment]
配置文件格式简化。主要是传入传出代理和路由部分。旧版格式仍然可用，但推荐尽快升级到最新格式。
优化了 GeoIP 的性能，减少了内存占用，提升了匹配效率。
这是他的更新说明
和配置文件有关系？

**Comment by xiaokaixuan** [comment]
@tislam8888 更新版本要修改Dockerfile中的下载地址  我的Releases里没有4.1

**Comment by tislam8888** [comment]
怎么修改release里的下载地址

**Comment by xiaokaixuan** [comment]
@tislam8888 可以了 更新了

**Comment by tislam8888** [comment]
谢谢你了
确实和服务端的v2raycore有关系
用你的重新部署 就可以用了

**Comment by tislam8888** [comment]
github.com/danishevskiyigor2/openshift-v2ray

帮忙看看 谢谢你了

**Comment by xiaokaixuan** [comment]
@tislam8888 新版的zip压缩包里少了一层路径，你自己研究下。如果经常翻墙的话，建议你买个VPS折腾。Openshift和Heroku只能临时用用。

**Comment by tislam8888** [comment]
我是个小白 不懂啊 什么路径

**Comment by xiaokaixuan** [comment]
那就用旧版本 暂时不要更新了

**Comment by xiaokaixuan** [comment]
@tislam8888 那就用旧版本 暂时不要更新了

**Comment by tislam8888** [comment]
大神 帮帮忙啊
我看了下 你说路径不同 确实是 解压包 多了两个文件夹
就是要改 Dockerfile 里面的 && unzip v2ray.zip \
后面的东西 能教教我吗

**Comment by xiaokaixuan** [comment]
@tislam8888 
![](https://user-images.githubusercontent.com/7234473/47988241-ba8df700-e11c-11e8-923b-2c2bb474e5a4.png)
v2ray-core经常升级，搞不懂你为何要跟着升级。这个功能后续升级就一直没改动过。

**Comment by tislam8888** [comment]
这一串代码 应该怎么改 我删了 v$VER-linux-64
还是不行

**Comment by xiaokaixuan** [comment]
@tislam8888  图都给你贴了  改成右边的

**Comment by tislam8888** [comment]
不好意思 刚才没有 刷新 没看见大神 你发的PP 谢谢了

**Comment by tislam8888** [comment]
好的 谢谢大神 啊 终于可以了 万份感激！
