### ISSUE TITLE
建立成功可是代理不过去

### ISSUE THREAD

**Issue by whhxmwhh** [xiaokaixuan/gost-heroku#3]
是否heroku启用新的机制。不让代理？

**Comment by xiaokaixuan** [comment]
刚试了下 没有问题

**Comment by whhxmwhh** [comment]
80端口？
![00捕获](https://user-images.githubusercontent.com/7959854/56789057-9b526580-6833-11e9-9f54-39a0527d587e.JPG)

**Comment by xiaokaixuan** [comment]
自己看下ReadMe里的使用方法  协议并不一样。。。
![image](https://user-images.githubusercontent.com/7234473/56789193-ebc9c300-6833-11e9-8a08-2e00dad2b4f6.png)

**Comment by whhxmwhh** [comment]
感谢您！我没有在deployed项目做链接！
